### ISSUE TITLE
geckodriver is not working!

### ISSUE THREAD

**Issue by pyronlaboratory** [buitron/geckodriver-buildpack#1]
I'm using this buildpack in conjugation with redistogo addon. However the geckodriver doesn't seem to launch and redis task won't initiate either!

```
def load_firefox_driver(proxy):
      options = webdriver.FirefoxOptions()

      options.add_argument('-headless')
      options.add_argument('-disable-gpu')
      options.add_argument('-no-sandbox')
      options.add_argument('-remote-debugging-port=9222')

      binary = FirefoxBinary(str(os.environ.get('FIREFOX_BIN')))
      
      anonymizer = Proxy({
          'proxyType': ProxyType.MANUAL,
          'httpProxy': proxy,
          'ftpProxy': proxy,
          'sslProxy': proxy
      })

      return webdriver.Firefox(firefox_binary=binary,executable_path=str(os.environ.get('GECKODRIVER_PATH')), proxy=anonymizer, firefox_options=options)

```
Here are the path variables I'm using:
```
FIREFOX_BIN:  /app/vendor/firefox/firefox.exe
GECKODRIVER_PATH:  /app/vendor/geckodriver.exe
```
Any idea what could have gone wrong here?

**Comment by pyronlaboratory** [comment]
I added an exception block to catch the error message:

`Message: invalid argument: can't kill an exited process`

**Comment by Manikaran20** [comment]
DId you get that working? @ronnielivingsince1994

**Comment by pyronlaboratory** [comment]
My chromedriver has kicked off. But still struggling with the geckodriver! How about you?

**Comment by Manikaran20** [comment]
> My chromedriver has kicked off. But still struggling with the geckodriver! How about you?

I thought I got it done but now facing other errors like "WebDriverException: Message: The browser appears to have exited before we could connect " which may be related to geckodriver and firefox paths. I'm using geckodriver-buildpack with firefox-buildpack and trying to run firefox("-headless"), no success tho.
